### ISSUE TITLE
Prerequisites -> Options after creating your account

### ISSUE THREAD

**Issue by skraljev** [apprenda/apprenda-ibm-cloud-workshop#3]
Prerequisites -> An Apprenda Platform account -> Create your account
- After provisioning the organization's environment, you are presented with option to start with tutorials, or skip tutorials and start with the developer portal. It would be good to document that and suggest proceeding by clicking on the link:  "Skip tutorials and go straight to the developer portal."

**Comment by danfhernandez** [comment]
Updated
