### ISSUE TITLE
Part 3 - Advise stopping and deleting the app at the end of workshop

### ISSUE THREAD

**Issue by skraljev** [apprenda/apprenda-ibm-cloud-workshop#6]
In Part 3 / At the end, just before the summary, it would be good to advise stopping and deleting the app so that it doesn't incur cost

**Comment by danfhernandez** [comment]
Updated to include this:
> IMPORTANT: When done with the app, make sure to stop and delete the app so that it doesn't incur cost with the following steps.
> 1. Navigate to Dashboard of app
> 2. Click Delete and confirm
