### ISSUE TITLE
Correct links to Part 2. and Part 3. in wiki pages

### ISSUE THREAD

**Issue by skraljev** [apprenda/apprenda-ibm-cloud-workshop#7]
After moving instructions to the wiki page, the links to the Part 2. and Part 3. should be updated to adhere to the new wiki structure.
- Go to the "1. Upload and Deploy a .NET App" chapter and scroll to the end.  Update the hyperlink under Part 2.
- Go to the "2. Configure Cloud Features" and correct the hyperlink under "Part 3."

**Comment by danfhernandez** [comment]
Updated
